version: "3.9"

services:

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrate
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./migrations:/app/migrations

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: unibuzz-api
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - APP_PORT=8080
    volumes:
      - .:/app
      - /app/tmp
    depends_on:
      migrate:
        condition: service_completed_successfully
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    container_name: unibuzz-worker
    restart: unless-stopped
    env_file:
      - .env