// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminAction = `-- name: CreateAdminAction :one
INSERT INTO admin_actions (
    admin_id,
    target_user_id,
    action_type,
    notes
) VALUES (
    $1,$2,$3,$4
)
RETURNING id, admin_id, target_user_id, action_type, notes, created_at
`

type CreateAdminActionParams struct {
	AdminID      pgtype.UUID
	TargetUserID pgtype.UUID
	ActionType   pgtype.Text
	Notes        pgtype.Text
}

func (q *Queries) CreateAdminAction(ctx context.Context, arg CreateAdminActionParams) (AdminAction, error) {
	row := q.db.QueryRow(ctx, createAdminAction,
		arg.AdminID,
		arg.TargetUserID,
		arg.ActionType,
		arg.Notes,
	)
	var i AdminAction
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TargetUserID,
		&i.ActionType,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVideoByAdmin = `-- name: DeleteVideoByAdmin :exec
UPDATE videos
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteVideoByAdmin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVideoByAdmin, id)
	return err
}
