// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAction struct {
	ID           pgtype.UUID
	AdminID      pgtype.UUID
	TargetUserID pgtype.UUID
	ActionType   pgtype.Text
	Notes        pgtype.Text
	CreatedAt    pgtype.Timestamp
}

type Comment struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	VideoID   pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Hashtag struct {
	ID  pgtype.UUID
	Tag string
}

type Report struct {
	ID          pgtype.UUID
	ReporterID  pgtype.UUID
	VideoID     pgtype.UUID
	Reason      pgtype.Text
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	Resolved    pgtype.Bool
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash string
	UserAgent        pgtype.Text
	IpAddress        pgtype.Text
	ExpiresAt        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	Revoked          pgtype.Bool
}

type User struct {
	ID              pgtype.UUID
	FullName        string
	Username        string
	Email           string
	PasswordHash    string
	UniversityName  pgtype.Text
	Course          pgtype.Text
	YearOfStudy     pgtype.Int4
	ProfilePhotoUrl pgtype.Text
	IsAdmin         pgtype.Bool
	IsSuspended     pgtype.Bool
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	DeletedAt       pgtype.Timestamp
}

type Video struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Caption         pgtype.Text
	VideoUrl        string
	ThumbnailUrl    pgtype.Text
	HlsUrl          pgtype.Text
	DashUrl         pgtype.Text
	DurationSeconds pgtype.Int4
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	DeletedAt       pgtype.Timestamp
}

type VideoHashtag struct {
	VideoID   pgtype.UUID
	HashtagID pgtype.UUID
}

type Vote struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	VideoID   pgtype.UUID
	VoteType  int16
	CreatedAt pgtype.Timestamp
}
