// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    reporter_id,
    video_id,
    reason,
    description
) VALUES (
    $1,$2,$3,$4
)
RETURNING id, reporter_id, video_id, reason, description, created_at, resolved
`

type CreateReportParams struct {
	ReporterID  pgtype.UUID
	VideoID     pgtype.UUID
	Reason      pgtype.Text
	Description pgtype.Text
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.VideoID,
		arg.Reason,
		arg.Description,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.VideoID,
		&i.Reason,
		&i.Description,
		&i.CreatedAt,
		&i.Resolved,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, reporter_id, video_id, reason, description, created_at, resolved
FROM reports
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListReportsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.VideoID,
			&i.Reason,
			&i.Description,
			&i.CreatedAt,
			&i.Resolved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReport = `-- name: ResolveReport :exec
UPDATE reports
SET resolved = TRUE
WHERE id = $1
`

func (q *Queries) ResolveReport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resolveReport, id)
	return err
}
