// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at
) VALUES (
    $1,$2,$3,$4,$5
)
RETURNING id, user_id, refresh_token_hash, user_agent, ip_address, expires_at, created_at, revoked
`

type CreateSessionParams struct {
	UserID           pgtype.UUID
	RefreshTokenHash string
	UserAgent        pgtype.Text
	IpAddress        pgtype.Text
	ExpiresAt        pgtype.Timestamp
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, expires_at, created_at, revoked
FROM sessions
WHERE refresh_token_hash = $1
AND revoked = FALSE
`

func (q *Queries) GetSessionByToken(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked = TRUE
WHERE user_id = $1
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked = TRUE
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}
