// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name,
    username,
    email,
    password_hash,
    university_name,
    course,
    year_of_study
) VALUES (
    $1,$2,$3,$4,$5,$6,$7
)
RETURNING id, full_name, username, email, password_hash, university_name, course, year_of_study, profile_photo_url, is_admin, is_suspended, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	FullName       string
	Username       string
	Email          string
	PasswordHash   string
	UniversityName pgtype.Text
	Course         pgtype.Text
	YearOfStudy    pgtype.Int4
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.UniversityName,
		arg.Course,
		arg.YearOfStudy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.UniversityName,
		&i.Course,
		&i.YearOfStudy,
		&i.ProfilePhotoUrl,
		&i.IsAdmin,
		&i.IsSuspended,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, username, email, password_hash, university_name, course, year_of_study, profile_photo_url, is_admin, is_suspended, created_at, updated_at, deleted_at FROM users
WHERE email = $1
AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.UniversityName,
		&i.Course,
		&i.YearOfStudy,
		&i.ProfilePhotoUrl,
		&i.IsAdmin,
		&i.IsSuspended,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, username, email, password_hash, university_name, course, year_of_study, profile_photo_url, is_admin, is_suspended, created_at, updated_at, deleted_at FROM users
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.UniversityName,
		&i.Course,
		&i.YearOfStudy,
		&i.ProfilePhotoUrl,
		&i.IsAdmin,
		&i.IsSuspended,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, username, email, password_hash, university_name, course, year_of_study, profile_photo_url, is_admin, is_suspended, created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.UniversityName,
			&i.Course,
			&i.YearOfStudy,
			&i.ProfilePhotoUrl,
			&i.IsAdmin,
			&i.IsSuspended,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const suspendUser = `-- name: SuspendUser :exec
UPDATE users
SET is_suspended = TRUE
WHERE id = $1
`

func (q *Queries) SuspendUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, suspendUser, id)
	return err
}

const unsuspendUser = `-- name: UnsuspendUser :exec
UPDATE users
SET is_suspended = FALSE
WHERE id = $1
`

func (q *Queries) UnsuspendUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unsuspendUser, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    full_name = $2,
    username = $3,
    university_name = $4,
    course = $5,
    year_of_study = $6,
    profile_photo_url = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, username, email, password_hash, university_name, course, year_of_study, profile_photo_url, is_admin, is_suspended, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID              pgtype.UUID
	FullName        string
	Username        string
	UniversityName  pgtype.Text
	Course          pgtype.Text
	YearOfStudy     pgtype.Int4
	ProfilePhotoUrl pgtype.Text
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.Username,
		arg.UniversityName,
		arg.Course,
		arg.YearOfStudy,
		arg.ProfilePhotoUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.UniversityName,
		&i.Course,
		&i.YearOfStudy,
		&i.ProfilePhotoUrl,
		&i.IsAdmin,
		&i.IsSuspended,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
