// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: videos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    user_id,
    caption,
    video_url,
    thumbnail_url,
    hls_url,
    dash_url,
    duration_seconds
) VALUES (
    $1,$2,$3,$4,$5,$6,$7
)
RETURNING id, user_id, caption, video_url, thumbnail_url, hls_url, dash_url, duration_seconds, created_at, updated_at, deleted_at
`

type CreateVideoParams struct {
	UserID          pgtype.UUID
	Caption         pgtype.Text
	VideoUrl        string
	ThumbnailUrl    pgtype.Text
	HlsUrl          pgtype.Text
	DashUrl         pgtype.Text
	DurationSeconds pgtype.Int4
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.UserID,
		arg.Caption,
		arg.VideoUrl,
		arg.ThumbnailUrl,
		arg.HlsUrl,
		arg.DashUrl,
		arg.DurationSeconds,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Caption,
		&i.VideoUrl,
		&i.ThumbnailUrl,
		&i.HlsUrl,
		&i.DashUrl,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, user_id, caption, video_url, thumbnail_url, hls_url, dash_url, duration_seconds, created_at, updated_at, deleted_at
FROM videos
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetVideoByID(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Caption,
		&i.VideoUrl,
		&i.ThumbnailUrl,
		&i.HlsUrl,
		&i.DashUrl,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRecentVideos = `-- name: ListRecentVideos :many
SELECT id, user_id, caption, video_url, thumbnail_url, hls_url, dash_url, duration_seconds, created_at, updated_at, deleted_at
FROM videos
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentVideosParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRecentVideos(ctx context.Context, arg ListRecentVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listRecentVideos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Caption,
			&i.VideoUrl,
			&i.ThumbnailUrl,
			&i.HlsUrl,
			&i.DashUrl,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByUser = `-- name: ListVideosByUser :many
SELECT id, user_id, caption, video_url, thumbnail_url, hls_url, dash_url, duration_seconds, created_at, updated_at, deleted_at
FROM videos
WHERE user_id = $1
AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListVideosByUser(ctx context.Context, userID pgtype.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Caption,
			&i.VideoUrl,
			&i.ThumbnailUrl,
			&i.HlsUrl,
			&i.DashUrl,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVideo = `-- name: SoftDeleteVideo :exec
UPDATE videos
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteVideo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteVideo, id)
	return err
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos
SET
    caption = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, caption, video_url, thumbnail_url, hls_url, dash_url, duration_seconds, created_at, updated_at, deleted_at
`

type UpdateVideoParams struct {
	ID      pgtype.UUID
	Caption pgtype.Text
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo, arg.ID, arg.Caption)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Caption,
		&i.VideoUrl,
		&i.ThumbnailUrl,
		&i.HlsUrl,
		&i.DashUrl,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
