// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: votes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVotes = `-- name: CountVotes :one
SELECT
    COALESCE(SUM(vote_type),0) AS score
FROM votes
WHERE video_id = $1
`

func (q *Queries) CountVotes(ctx context.Context, videoID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, countVotes, videoID)
	var score interface{}
	err := row.Scan(&score)
	return score, err
}

const removeVote = `-- name: RemoveVote :exec
DELETE FROM votes
WHERE user_id = $1
AND video_id = $2
`

type RemoveVoteParams struct {
	UserID  pgtype.UUID
	VideoID pgtype.UUID
}

func (q *Queries) RemoveVote(ctx context.Context, arg RemoveVoteParams) error {
	_, err := q.db.Exec(ctx, removeVote, arg.UserID, arg.VideoID)
	return err
}

const upsertVote = `-- name: UpsertVote :one
INSERT INTO votes (
    user_id,
    video_id,
    vote_type
) VALUES (
    $1,$2,$3
)
ON CONFLICT (user_id, video_id)
DO UPDATE SET vote_type = EXCLUDED.vote_type
RETURNING id, user_id, video_id, vote_type, created_at
`

type UpsertVoteParams struct {
	UserID   pgtype.UUID
	VideoID  pgtype.UUID
	VoteType int16
}

func (q *Queries) UpsertVote(ctx context.Context, arg UpsertVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, upsertVote, arg.UserID, arg.VideoID, arg.VoteType)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoID,
		&i.VoteType,
		&i.CreatedAt,
	)
	return i, err
}
